name: analyse_api
on: [push]
jobs:
  build-test:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          configuration: api/phpstan.neon
          memory_limit: 2048M
          level: max
          php_version: 8.1
