services:
  api:
    image: thecodingmachine/php:8.2-v4-apache
    environment:
      # PHP EXTENSIONS
      PHP_EXTENSION_GD: 1
      # GLOBAL ENVIRONMENT
      APACHE_DOCUMENT_ROOT: public
      # LARAVEL SPECIFICS
      APP_NAME: ${APP_NAME}
      APP_ENV: ${ENV}
      APP_DEBUG: ${DEBUG}
      APP_URL: ${HTTP_PROTOCOL}://${DOMAIN}
      IP_ADDRESS: ${IP_ADDRESS}
      HTTP_PROTOCOL: ${HTTP_PROTOCOL}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      # DATABASE
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: ${DB_HOST}
      DEFAULT_USERNAME: ${DEFAULT_USERNAME}
      DEFAULT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      # EMAILING
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_VERIFY_PEER: ${MAIL_VERIFY_PEER}
      # GOOGLE
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      VITE_GOOGLE_CLIENT_SECRET: ${VITE_GOOGLE_CLIENT_SECRET}
      VITE_GOOGLE_REDIRECT_URI: ${VITE_GOOGLE_REDIRECT_URI}
      # GITHUB
      VITE_GITHUB_CLIENT_ID: ${VITE_GITHUB_CLIENT_ID}
      VITE_GITHUB_CLIENT_SECRET: ${VITE_GITHUB_CLIENT_SECRET}
      VITE_GITHUB_REDIRECT_URI: ${VITE_GITHUB_REDIRECT_URI}
      # CRON
      TZ: Europe/Paris
      CRON_USER: root
      CRON_SCHEDULE: ${API_CRON_SCHEDULE}
      CRON_COMMAND: php artisan schedule:run
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN}`, `${IP_ADDRESS}`)
