services:
  database:
    image: mysql:8.0
    volumes:
      - database_volume_thelabs:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: ${DB_HOST}

volumes:
  database_volume_thelabs:
