services:
  backend:
    build:
      context: ../backend
      target: backend-local
      args:
        DOCKER_UID: ${DOCKER_UID-1000}
        DOCKER_GID: ${DOCKER_GID-1000}
    volumes:
      - ../backend:/var/www/html/:delegated
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  backend_webserver:
    build:
      context: ../backend
      target: webserver-local
    volumes:
      - ../backend:/var/www/html/:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_webserver.rule=Host(`backend.${DOMAIN}`)

  backend_cron:
    extends: backend
    build:
      context: ../backend
      target: backend-cron-local

  backend_vite:
    image: thecodingmachine/nodejs:v2-18-bullseye
    volumes:
      - ../backend:/usr/src/app/:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_vite.rule=Host(`backend.vite.${DOMAIN}`)
      - traefik.http.services.backend_vite.loadbalancer.server.port=5173
    environment:
      # STARTUP COMMANDS
      APP_URL: ${HTTP_PROTOCOL}://backend.${DOMAIN}
      STARTUP_COMMAND_1: yarn
      STARTUP_COMMAND_2: yarn dev --host
      VITE_SERVER_HMR_PORT: 80
      VITE_SERVER_HMR_HOST: backend.vite.${DOMAIN}