name: CI

on: [ push ]


env:
  DAY_OF_WEEK: Monday

jobs:
  analyse_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Validate composer
        run: composer validate --strict --working-dir=./api/

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./api/

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: "./api/"
          configuration: "./api/phpstan.neon"
          memory_limit: 2048M
          level: max
          php_version: "8.1"