name: "Static Analysis"

on: [ push ]

env:
  DAY_OF_WEEK: Monday

jobs:
  analyse_api:
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.0", "8.1", "8.2" ]
        laravel: [ "^9.0", "^10.0" ]

    name: "PHP ${{ matrix.php }} - L${{ matrix.laravel }}"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: "Validate composer"
        run: "composer validate --strict --working-dir=./api/"

      - name: "Install dependencies from composer.json"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress --working-dir=./api/"


#      - name: "PHPStan Static Analysis"
#        uses: "php-actions/phpstan@v3"
#        with:
#          path: ./api/
#          configuration: ./api/phpstan.neon
#          memory_limit: 2048M
#          level: max
#          php_version: "8.1"