name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3



      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=./api/
        with:
          php_version: "8.1"

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: "./api/src/"
          configuration: "api/phpstan.neon"
          memory_limit: 2048M
          level: max
          php_version: "8.1"