name: "PHPStan dev"

on: [push]

jobs:
  phpstan-dev:
    strategy:
      matrix:
        php: ["8.1"]
        laravel: ["^9.0"]
      fail-fast: false

    name: "P${{ matrix.php }} - L${{ matrix.laravel }}"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          coverage: "none"

      - name: "Require PHPStan dev version"
        run: "composer require phpstan/phpstan:@dev --no-update --no-interaction --no-progress --working-dir=./api/"

      - name: "Install highest dependencies from composer.json"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress --working-dir=./api/"

      - name: "Execute static analysis"
        uses: "php-actions/phpstan@v3"
        with:
        path: "./api"
        php_version: "${{ matrix.php }}"
        level: max
        autoload_file: "./api/vendor"
        configuration: "./api/phpstan.neon"